name: dio_isolate_pro
description:  A dio transformer espically for flutter, by which the json decoding will be in background with [compute] function in flutter sdk.

version: 5.6.0
homepage: https://github.com/arklabsnz/dio_flutter_transformer

environment:
  sdk: ">3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: